const lessonTitle = "猫捕雀";

const lessonData = [
    // ===== 第1段 =====
    ["窗外", "chuāng wài", "Outside the window", "Di luar tingkap"],
    ["有", "yǒu", "there was", "ada", "有"],
    ["枣林", "zǎo lín", "jujube grove", "hutan jujube", "枣树林"],
    ["，", "", "", "", ""],
    ["雏雀", "chú què", "young sparrows", "burung pipit muda", "幼小的麻雀"],
    ["习飞", "xí fēi", "practising flying", "berlatih terbang", "练习飞翔"],
    ["其下", "qí xià", "under it", "di bawahnya", "在树下"],
    ["。", "", "", "", ""],
    ["一日", "yí rì", "One day", "Suatu hari", "有一天"],
    ["，", "", "", "", ""],
    ["猫", "māo", "cat", "kucing", "猫"],
    ["蔽身", "bì shēn", "hid itself", "menyembunyikan diri", "隐蔽身体"],
    ["林间", "lín jiān", "among the trees", "di antara pokok-pokok", "树林间"],
    ["，", "", "", "", ""],
    ["突", "tū", "suddenly", "tiba-tiba", "突然"],
    ["噬", "shì", "bit", "menggigit", "咬死"],
    ["雀母", "què mǔ", "mother sparrow", "ibu pipit", "母雀"],
    ["。", "", "", "", ""],
    ["其", "qí", "Its", "Ia punya", "它的"],
    ["雏", "chú", "young ones", "anak-anak", "幼鸟"],
    ["四五", "sì wǔ", "four or five", "empat lima", "四五只"],
    ["，", "", "", "", ""],
    ["噪", "zào", "chirped", "berbunyi riuh", "鸣叫"],
    ["而", "ér", "and", "dan", "并"],
    ["逐", "zhú", "chased", "mengejar", "追赶"],
    ["猫", "māo", "the cat", "kucing", "猫"],
    ["，", "", "", "", ""],
    ["每进", "měi jìn", "each advance", "setiap kali maju", "每次向前"],
    ["益", "yì", "more and more", "semakin", "更加"],
    ["怒", "nù", "angry", "marah", "愤怒"],
    ["。", "", "", "", ""],
    ["猫", "māo", "The cat", "Kucing", "猫"],
    ["奋", "fèn", "vigorously", "dengan kuat", "奋力"],
    ["攫", "jué", "grabbed", "menangkap", "抓取"],
    ["之", "zhī", "them", "mereka", "它们"],
    ["，", "", "", "", ""],
    ["不胜", "bù shèng", "could not overcome", "tidak dapat mengalahkan", "敌不过"],
    ["，", "", "", "", ""],
    ["反", "fǎn", "instead", "sebaliknya", "反而"],
    ["奔", "bēn", "ran", "berlari", "跑"],
    ["入室", "rù shì", "into the room", "masuk ke dalam bilik", "进屋"],
    ["。", "", "", "", ""],
    ["雀母", "què mǔ", "The mother sparrow", "Ibu pipit", "母雀"],
    ["死", "sǐ", "died", "mati", "死了"],
    ["，", "", "", "", ""],
    ["其", "qí", "its", "ia punya", "它的"],
    ["雏", "chú", "young ones", "anak-anak", "幼鸟"],
    ["绕室", "rào shì", "circling the room", "mengelilingi bilik", "绕着屋子"],
    ["啁啾", "zhōu jiū", "chirping", "berbunyi", "啾啾地叫"],
    ["，", "", "", "", ""],
    ["飞入室者", "fēi rù shì zhě", "those that flew into the room", "yang terbang masuk ke dalam bilik", "飞进屋的"],
    ["三", "sān", "three times", "tiga kali", "三次"],
    ["。", "", "", "", ""],
    ["越", "yuè", "After", "Selepas", "过了"],
    ["数日", "shù rì", "several days", "beberapa hari", "几天"],
    ["，", "", "", "", ""],
    ["犹", "yóu", "still", "masih", "仍然"],
    ["望室", "wàng shì", "looked towards the room", "memandang ke arah bilik", "望着屋子"],
    ["而噪也", "ér zào yě", "and chirped", "dan berbunyi", "鸣叫"],
    ["。", "", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["哀哉", "āi zāi", "Alas", "Aduh", "可悲啊"],
    ["！", "", "", "", ""],
    ["猫", "māo", "the cat", "kucing", "猫"],
    ["一搏", "yī bó", "one pounce", "satu serangan", "一扑"],
    ["而", "ér", "and", "dan", "就"],
    ["夺", "duó", "snatched away", "merampas", "夺走"],
    ["四五", "sì wǔ", "four or five", "empat lima", "四五只"],
    ["雏", "chú", "young ones'", "anak-anak", "幼鸟的"],
    ["之母", "zhī mǔ", "mother", "ibu", "母亲"],
    ["，", "", "", "", ""],
    ["人", "rén", "people", "manusia", "人们"],
    ["虽", "suī", "although", "walaupun", "虽然"],
    ["不及", "bù jí", "could not", "tidak sempat", "来不及"],
    ["救之", "jiù zhī", "save them", "menyelamatkan mereka", "救它们"],
    ["，", "", "", "", ""],
    ["未有", "wèi yǒu", "there is no one", "tiada siapa", "没有不"],
    ["不恻焉", "bù cè yān", "who is not saddened", "yang tidak berasa sedih", "不感到悲伤的"],
    ["慨于中者", "kǎi yú zhōng zhě", "with pity in their hearts", "dengan perasaan belas kasihan dalam hati", "内心感慨的"],
    ["。", "", "", "", ""],
    ["而", "ér", "But", "Tetapi", "而"],
    ["猫", "māo", "the cat", "kucing", "猫"],
    ["且", "qiě", "moreover", "lagi pula", "且"],
    ["眈眈然", "dān dān rán", "with a greedy look", "dengan pandangan yang tamak", "贪婪地盯着"],
    ["，", "", "", "", ""],
    ["惟恐", "wéi kǒng", "only afraid", "hanya takut", "只怕"],
    ["不尽", "bù jìn", "not fully", "tidak habis", "不把……消灭干净"],
    ["其类", "qí lèi", "its kind", "jenisnya", "它的同类"],
    ["焉", "yān", "particle", "lah", "呢"],
    ["。", "", "", "", ""],
    ["呜呼", "wū hū", "Alas", "Aduhai", "哎呀"],
    ["，", "", "", "", ""],
    ["何其", "hé qí", "how", "betapa", "多么"],
    ["性之忍也", "xìng zhī rěn yě", "cruel is its nature", "kejamnya sifat", "性情残忍啊"],
    ["！", "", "", "", ""],
    ["物与物", "wù yǔ wù", "Creature against creature", "Makhluk dengan makhluk", "生物与生物"],
    ["相残", "xiāng cán", "harming each other", "saling membinasakan", "互相残杀"],
    ["，", "", "", "", ""],
    ["人", "rén", "people", "manusia", "人们"],
    ["且", "qiě", "even", "malahan", "尚且"],
    ["恶之", "wù zhī", "despise it", "meluat dengannya", "厌恶它"],
    ["；", "", "", "", ""],
    ["乃有", "nǎi yǒu", "yet there are", "tetapi ada", "竟然有"],
    ["凭", "píng", "rely on", "bergantung pada", "凭借"],
    ["权位", "quán wèi", "power and position", "kuasa dan kedudukan", "权势地位"],
    ["，", "", "", "", ""],
    ["张", "zhāng", "extend", "menghulurkan", "张开"],
    ["爪牙", "zhǎo yá", "claws and teeth", "cakar dan taring", "爪牙"],
    ["，", "", "", "", ""],
    ["残民", "cán mín", "harm the people", "mencederakan rakyat", "残害百姓"],
    ["以", "yǐ", "in order to", "untuk", "来"],
    ["自肥者", "zì féi zhě", "enrich themselves", "menguntungkan diri sendiri", "使自己富足的人"],
    ["，", "", "", "", ""],
    ["何也", "hé yě", "why", "kenapa", "为什么呢"],
    ["？", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["薛福成", "xuē fú chéng", "Xue Fucheng", "Xue Fucheng", "薛福成"],
    ["《", "", "", "", ""],
    ["猫捕雀", "māo bǔ què", "The Cat Catches a Sparrow", "Kucing Menangkap Burung Pipit", "猫捕雀"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
